export enum ErrorCode {
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
	EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
	CONTROLLER_NOT_FOUND = "CONTROLLER_NOT_FOUND",
	CONTROLLER_ALREADY_EXISTS = "CONTROLLER_ALREADY_EXISTS",
	CONTROLLER_ASSIGNMENT_NOT_FOUND = "CONTROLLER_ASSIGNMENT_NOT_FOUND",
	CONTROLLER_ASSIGNMENT_ALREADY_EXISTS = "CONTROLLER_ASSIGNMENT_ALREADY_EXISTS",
	AIRPORT_NOT_FOUND = "AIRPORT_NOT_FOUND",
	POSITION_NOT_FOUND = "POSITION_NOT_FOUND",
	INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
	INSUFFICIENT_QUALIFICATION = "INSUFFICIENT_QUALIFICATION",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
